---
nats_to_syslog/nats_to_syslog_linux_amd64.tar.gz:
  object_id: 5d5d32dc-946c-4a27-9786-df4689706cdb
  sha: d27c56da9cdf214ed39a471f0ca5c970abbd510d
  size: 2094679
ruby2.3/bundler-1.11.2.gem:
  object_id: ce2c212f-c2ff-440e-9f4b-c2c214a010f9
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
  size: 263168
ruby2.3/rake-11.2.2.gem:
  object_id: 757c960e-1536-4be2-b0d9-d4f587e4c6ab
  sha: 879e7c02b1a0b37333a91f11621f798deb874b6e
  size: 102400
ruby2.3/rubygems-2.6.4.tgz:
  object_id: 4f90feb0-d0cf-41d8-a191-9b63e6f08f27
  sha: 8ef39e536af2ecd20b0e7a95765fa6a485087ac8
  size: 478582
ruby2.3/ruby-2.3.1.tar.gz:
  object_id: 0ab54e2b-3919-4e52-b157-50c8a7704cad
  sha: c39b4001f7acb4e334cb60a0f4df72d434bef711
  size: 17797997
logstash/logstash-filter-alter-3.0.0.zip:
  object_id: 8b0c5aa7-4675-4659-8b0a-78ebb6cd6b0c
  sha: f7169d5bc42e99c3a89afadd5a838c4e4e0105ab
  size: 6642
logstash/logstash-filter-translate-3.0.1.zip:
  object_id: 33680669-f431-43ac-9b83-c1b995617f47
  sha: e01978407ca5a4f4a9f48d1fd04f8ad3e721e679
  size: 9437
java8/openjdk-1.8.0_121.tar.gz:
  object_id: 18a9e955-f23f-455c-a8d2-3c676ece003a
  sha: d1596c9c825cb3f5be373bd34e4f6520187b9660
  size: 45476711
curator/elasticsearch-curator-4.2.6.tar.gz:
  object_id: a65edd77-82e3-4467-bdd4-0118b983a3ee
  sha: 3a4f620da0df6f73ed4b82a0d7b99156c35a3479
  size: 135837
curator/elasticsearch-curator-requirements.tar.gz:
  object_id: 2cda467f-504f-4714-a800-0b60183d41ef
  sha: bd938b1607174c45bb4b82d3ea983d5bc784e081
  size: 1384284
python/Python-3.6.1.tgz:
  object_id: db2b3522-9d58-4998-81ec-237d900ad740
  sha: 6e91434cf22414af8240dfa1bf8ab2d043b04998
  size: 22540566
haproxy/haproxy-1.6.11.tar.gz:
  object_id: aef31767-d5e2-4937-8391-08f3c5eb2c30
  sha: 8c1c1b2346cf18379cd798fbc6364fdab5e17d32
  size: 1574029
haproxy/pcre-8.40.tar.gz:
  object_id: edf51dad-4c6c-4a3d-8ebb-3a9b9f9641e5
  sha: 10384eb3d411794cc15f55b9d837d3f69e35391e
  size: 2065161
logstash/logstash-input-relp-3.0.0.zip:
  object_id: a37173e4-e190-4ab6-bd90-83a84ff31fdc
  sha: 98076907db434d88f14767afe54e867433453ac2
  size: 11670
cerebro/cerebro-0.6.3.tgz:
  object_id: 229f802d-38d2-4d5e-a008-d27435a4fac6
  sha: 03c7c8549badc7d3416a170973816652c204553f
  size: 51195857
redis/redis-3.2.8.tar.gz:
  object_id: 15e19594-4fec-44f5-9070-87e15a767f31
  sha: 6780d1abb66f33a97aad0edbe020403d0a15b67f
  size: 1547237
elasticsearch/elasticsearch-5.3.0.tar.gz:
  object_id: d4c5f596-b323-497a-916b-0081034ad59f
  sha: 9273fdecb2251755887f1234d6cfcc91e44a384d
  size: 33696963
kibana/kibana-5.3.0-linux-x86_64.tar.gz:
  object_id: 001b3f9a-7bb7-44eb-b90c-7e1d44e0056c
  sha: 4e9daf275f8ef749fba931c1f5c35f85662efd53
  size: 38912478
logstash/logstash-5.3.0.tar.gz:
  object_id: dc079ef3-83e3-4487-9303-76e0eaa13c2e
  sha: ede53a40e2935768e8113b63c1a09160f849b6c4
  size: 94087323
