# --
# Default values + enabled logstash debug
# --
properties:
  logstash_ingestor:
    syslog:
      port: 5514
  logstash_parser:
    debug: true
    outputs: [ { plugin: "elasticsearch", options: {} } ]
    elasticsearch:
      document_id: ~
      index: "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
      index_type: "%{@type}"
      data_hosts: [127.0.0.1]
      flush_size: 500
